modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="forge_mod"          # <— geändert!
version="1.0.0"
displayName="Duel Mod"
description='''
Eine Mod, die Duelle zwischen Spielern ermöglicht.
'''
authors="Extrahelden Team"

[[dependencies.forge_mod]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.forge_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
